version: '3.4'

services:
  proxy:
    build: proxy
    restart: always
    container_name: Hosting-Container-SSH-Proxy
    environment:
      - VIRTUAL_HOST=test2.container.mireu.xyz
    depends_on:
      - api

  api:
    image: registry.gitlab.com/mireu-lab/docker-ssh-conteiner:ubuntu
    restart: always
    container_name: Hosting-SSH-Container
    ports:
      - "1212:22"

networks:
  default:
    external:
      name: Container_Proxy_Network